### ISSUE TITLE
README seems too generic

### ISSUE THREAD

**Issue by mcasper3** [jaysanatez/score_board#3]
I think you should include more information about your specific application in the README. Otherwise, I have no idea what this project is about.

**Comment by Brobin** [comment]
Also, only scrubs don't have demos. You should get on that.

**Comment by jaysanatez** [comment]
I don't want to give away too much. You guys are probably trying to steal my ideas.

**Comment by Brobin** [comment]
Nah, we're just trying to help. If you notice in c4b9d9d4f8d99db9d838742fc3ee2a2d0457404e, you said "Bring ScoreBoard online", yet it's not online.

**Comment by jaysanatez** [comment]
The codebase is 100% online. I believe commit c4b9d9d4f8d99db9d838742fc3ee2a2d0457404e added it to the remote repository.
